services:
  k-api:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file: docker/app/.env
    ports: 
      - "8000:8000"
    depends_on: 
      - opensearch
    environment:
      - LOG_TO_FILE=true
      - LOG_DIR=/var/log/app
  opensearch:
    build:
      context: .
      dockerfile: docker/opensearch/Dockerfile
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Zkzkdhqodzm12#
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    depends_on: 
      - opensearch
      - k-api
    volumes:
      - ./logs:/var/log/app:ro
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile