version: "3.8"
services:
  api:
    build: .
    env_file: .env
    volumes: 
      - ".:/app"
      - "./logs:/var/log/app"
    ports: 
      - "8000:8000"
    depends_on: 
      - opensearch
      - redis
    environment:
      - LOG_TO_FILE=true
      - LOG_DIR=/var/log/app
  redis:
    image: redis:7
    ports: 
      - "6379:6379"
  opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Wlelqlflvhxm12#
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    depends_on: 
      - opensearch
    volumes:
      - ./logs:/var/log/app:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
